---
title: "Population Exploration"
author:  "Mofi Islam and Dennis Wollersheim "
date: "2018-11-19 "
output:
  workflowr::wflow_html:
    toc: false
---

```{r pre_initial, echo=FALSE, results='hide', message=FALSE, warning=FALSE}

rm(list=ls())
options(width = 200)
show_code = FALSE
source("lib/functions.R")
source("lib/standardisation.R")
source("lib/get_data.R")
source("lib/generate_data_frames.R")
source("lib/findOverlap.R")
library('tidyverse')
opts_chunk$set(echo = FALSE)

```


```{r initial, results='hide', message=FALSE, warning=FALSE}

dataset="_rr"
dataset=""
get_data_from_cache(dataset = dataset)
source('lib/findOverlap_simplified.R')

```


```{r generate_continuing_users }
#
tic('generate_continuing_users')
df%>%
  group_by(pin) %>%
  summarise( 
            n_quarter = n_distinct( quarter ),
            usage_category= cut( n_quarter, 
                                c(-1, 1,6,11, 18), 
                                labels = qw("one-off medium-episodic long-episodic chronic")),
                                ordered_result=TRUE
            ) %>%
  {.} -> df_patient_usage
toc()

```


```{r count_simple_episodes}


tic('count_simple_episodes')

df_dd_0_new %>%
  rename( supply_date = supply_date.opioid ) %>%
  rename( supply_year  = supply_year.opioid) %>%
  distinct( pin, supply_year, supply_date ) %>%
  count( pin, supply_year ) %>% 
  { . } -> df_dd_0_episodes


df_dd_overlap_all %>%
  filter( supply_date.opioid != supply_date.benzo) %>%
  rename( supply_date  = supply_date.opioid) %>%
  rename( supply_year  = supply_year.opioid) %>%
  distinct( pin, supply_year, supply_date ) %>%
  count( pin, supply_year ) %>% 
  { . } -> df_dd_overlap_episodes

df_dd_overlap_episodes %>%
  full_join( df_dd_0_episodes, by=c( 'pin', 'supply_year')) %>%
  mutate( n.x = ifelse( is.na( n.x  ), 0, n.x ), 
         n.y = ifelse( is.na( n.y  ), 0, n.y ) ) %>%
  mutate( n = n.y+n.x ) %>% 
  { . } -> df_dd_all_episodes

```
# compare_users_continuing_vs_dd 

```{r compare_users_continuing_vs_dd }
df_patient_usage %>%
  inner_join( df_patient ) %>%
  left_join( df_dd_all_episodes %>% count( pin ), by='pin') %>%
  mutate( n = ifelse( is.na(n) , 0 )) %>%
  print()


```


```{r  compare_continuing_vs_episodes}


```


```{r  compare_users_continuing_vs_dd}


```


```{r  compare_users_continuing_vs_dd}


```


```{r }


```


```{r }


```


```{r }


```


```{r }


```


```{r }











```


```{r }


```


```{r get_continuing_users}

df_dd_overlap_all %>%
  count( pin ) %>%
  full_join ( df_patient_usage %>% 
             filter( drug_type == 'opioid')
           , by = 'pin' ) %>% 
  mutate( is_dd = ifelse( is.na(n), 'not_dd', 'dd') ) %>%
  { . } -> df_match


cat ('# number of users who do not double dip ')

df_match %>%
  count( is_dd ) 

cat ('# ratio of double dippers for each usage category')

df_match %>% 
  count( usage_category, is_dd) %>% 
  spread( is_dd, nn ) %>%
  mutate( ratio_dd = dd/not_dd )


df_match %>% 
  inner_join( df_patient ) %>%
  count( lga, usage_category, is_dd) %>% 
  spread( is_dd, nn ) %>%
  mutate( ratio_dd = dd/not_dd ) %>%
  filter( lga != '.' ) %>%
  filter( usage_category == 'regular') %>%
  right_join( df_population %>% distinct( lga ) ) %>%
  mutate( ratio_dd = ifelse( is.na( ratio_dd), 0, ratio_dd )) %>%
  mutate( value = cut( ratio_dd, 
                    breaks=quantile( ratio_dd, probs=seq(0,1,1/3) ), 
                    labels=qc( low, medium, high ))
  ) %>%
  mutate( value = factor( ifelse( is.na( value ), 1, value ),
                         labels=qc( low, medium, high )  )) %>%
  print_map( title="Ratio between dd and regular users", filename='/tmp/dd_regular.png', inset_states=c(1,2,4:6 ) ) -> a
  

df_match %>% 
  inner_join( df_patient ) %>%
  count( lga, usage_category, is_dd) %>% 
  spread( is_dd, nn ) %>%
  mutate( ratio_dd = dd/not_dd ) %>%
  filter( lga != '.' ) %>%
  filter( usage_category == 'one-off') %>%
  right_join( df_population %>% distinct( lga ) ) %>%
  mutate( ratio_dd = ifelse( is.na( ratio_dd), 0, ratio_dd )) %>%
  mutate( value = cut( ratio_dd, 
                      breaks=quantile( ratio_dd, probs=seq(0,1,1/3) ), 
                      labels=qc( low, medium, high ))
  ) %>%
  mutate( value = factor( ifelse( is.na( value ), 1, value ),
                         labels=qc( low, medium, high )  )) %>%
  print_map( title="Ratio between dd and one-off users", filename='/tmp/dd_one-off.png', inset_states=c(1,2,4:6 ) ) -> a
```

```{r prediction_dd}
library( caret )


df_patient %>% filter( lga != '.' ) %>% mutate( s1 = substring( lga, 1,1)) %>% distinct( state, s1 ) %>% arrange( s1 )
df_population %>% filter( lga != '.' ) %>% mutate( s1 = substring( lga, 1,1)) %>% distinct( state, s1 ) %>% arrange( s1 )

df_match %>% 
  inner_join( df_patient ) %>%
  select( -state, -pin, -drug_type ) %>%
  inner_join( df_population %>% 
             filter( supply_year=='2013' ) %>%
             group_by( lga, seifa, urbanization, state, irsd_score_raw, area_albers_sqkm ) %>% 
             summarise( density=sum( population ) / min(area_albers_sqkm)) , 
           by='lga') %>% 
  mutate( is_dd = factor( is_dd ),  state = factor( get_state_code_from_lga( lga) )) %>%
  select( -n, -lga, -area_albers_sqkm ) %>%
  drop_na() %>%
{ . } -> df_prediction
#
intrain <- createDataPartition(y =  df_prediction$is_dd, p= 0.7, list = FALSE)
training <- df_prediction[intrain,]
testing <- df_prediction[-intrain,]
MyTrainControl=trainControl(
                            method = "repeatedcv",
                            number=5,
                            repeats=5
)


rf_fit <- train(is_dd ~ .,
                data = training, 
                method = "rpart",
                trControl=MyTrainControl, 
                preProcess=  c("center", "scale", "YeoJohnson"), 
                tuneGrid = expand.grid(nIter=1:10*10) 
                )
#
#

 

```

